meta_product_name: "Golf Pal"
meta_title: "Golf Pal - Play Together Play Better"
meta_description: "gottaloveit"
meta_image: "favicon.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
