meta_product_name: "Golf Pal"
meta_title: "Golf Pal - Play Together Play Better"
meta_description: "Book your favourite golf courses with your friends, each can pay for themselves and update the scorecard from the app. Welcome to the future of golf."
meta_image: "fbbkg.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
